### PR TITLE
UI Readability Improvements For Dashboard

### PR DESCRIPTION
**Pull request by FinnCastro**
Fixed width and readability on all sections (improving slippage especially).

### CODE REVIEW

**Comment by saml33** [comment]
Thanks. A few things we can do still:

Make the table cells consistent and add padding-left (cells have different heights)
The column headers blend into the rest of the data. Could do with some different styling
Would be better if the overflow was only on the table
Make the filter inputs the same height
Remove double borders where tabs/table is touching other borders
The key down the bottom could use some styling/improving. Maybe better at the top?

**Comment by abrzezinski94** [comment]
looks good to me when @saml33 approve its good to go

**Comment by FinnCastro** [comment]
Update:

- RenderValue added to selector to allow for selector to display different value to its state.
- Table cells consistent,
- Column headers styled,
- Overflow implemented,
- Stickiness on first column and header,
- Double borders removed,
- Annotations implemented,

Lmk any further improvemements.

**Comment by abrzezinski94** [comment]
> Update:
> 
> * RenderValue added to selector to allow for selector to display different value to its state.
> * Table cells consistent,
> * Column headers styled,
> * Overflow implemented,
> * Stickiness on first column and header,
> * Double borders removed,
> * Annotations implemented,
> 
> Lmk any further improvements.

@saml33

**Pull request merged**
