### PR TITLE
Mango Mints

### PR DESCRIPTION
**Pull request by saml33**
For preview only.

### CODE REVIEW

**Comment by tlrsssss** [comment]
Preview link: https://mango-v4-pro4lksqq-blockworks-foundation.vercel.app/

**Comment by tlrsssss** [comment]
Hm I clicked on the link at the top to view the mango mints and then switched wallets and now I don't see a way to view the mango mints page.

**Comment by mschneider** [comment]
Depending on the average trade size and activity every user will be assigned to a league.

1. All new accounts are “Seeds” by default.
2. “Bots” get manually assigned by our own off-chain analysis bots stay bots forever.
3. At the end of their first season all “Seeds” become either a “Mango” or a “Whale” (accounts with average trade sizes above $1000)
4. If a “Whale” doesn’t trade large enough size, they become a “Mango”.

**Comment by mschneider** [comment]
How it works could just scroll down to FAQ, the modal is really hard to read

**Comment by mschneider** [comment]
The leaderboard doesn't link to the actual accounts, the address variable is not resolved

**Comment by saml33** [comment]
> My wallet is already whitelisted but after clicking the "Get Ready" link I see a popup about white listing the wallet. Is that expected?

No, if your whitelisted this won't show

> Should the tier amount for "Mango" and "Whale" be the same $? They're both $1k

Mango is < $1k and Whale > $1k

> Can the "How it Works" link be more visible? It took me awhile to find it. Perhaps adding a icon, or larger size, or even as a button. I think that will be an important first thing users should see.

Yep, for sure

**Comment by saml33** [comment]
> How it works could just scroll down to FAQ, the modal is really hard to read

Sounds good to me

**Review by tlrsssss — APPROVED** [review]

**Pull request merged**
