### PR TITLE
Add privacy toggle to PerpPositions

### PR DESCRIPTION
**Pull request by Lou-Kamades**

### CODE REVIEW

**Comment by saml33** [comment]
I think we should do this app-wide if we're going to do it. Can be a setting in AccountSettings "Private Mode". Then all sensitive account numbers can be masked with **** or something like that. Could also add the toggle to the actions menu on the account page

**Comment by saml33** [comment]
Think this should be off by default.

Did you try * for the masked state? Another option that could be nice would be to css blur the numbers.

Do you think balances should be masked too?

**Comment by Lou-Kamades** [comment]
I really like how the blur looks: 
Screenshot 2023-08-17 at 12 59 07 AM
Screenshot 2023-08-17 at 12 59 20 AM

**Comment by Lou-Kamades** [comment]
**** isn't bad, but a little less appealing imo:
Screenshot 2023-08-17 at 12 47 51 AM
Screenshot 2023-08-17 at 12 48 06 AM

**Comment by Lou-Kamades** [comment]
> Do you think balances should be masked too?
Imo no, it gets pretty difficult to use the site if that's the case -- but ofc that's just my opinion

Screenshot 2023-08-17 at 1 08 26 AM
Screenshot 2023-08-17 at 1 08 43 AM

**Comment by saml33** [comment]
When the toggle is false before you interact with it, privacy mode is true.

I think you could have the switch in account actions menu rather than an extra step with the modal

The issue with the blur is it changes intensity depending on font size. My preference is **** can request a review from tlrsssss and see what he thinks

**Pull request merged**
