### PR TITLE
add bottom status bar

### PR DESCRIPTION
**Pull request by saml33**
Screen Shot 2023-08-07 at 9 29 41 pm

### CODE REVIEW

**Comment by tlrsssss** [comment]
I guess I was expecting it would be fixed to the bottom of the window and not need to scroll.  Is there a tradeoff for one or the other? @microwavedcola1

**Comment by microwavedcola1** [comment]
> I guess I was expecting it would be fixed to the bottom of the window and not need to scroll. Is there a tradeoff for one or the other? @microwavedcola1

I also expect fixed like tyler

**Comment by saml33** [comment]
@tlrsssss @microwavedcola1 I guess I'm not sure it's important enough to take up space in the window. It could be with more info on the status of the platform. Will see how it feels when fixed. Will make the height as small as possible without looking strange

**Comment by saml33** [comment]
@tlrsssss @microwavedcola1 Fixed to the bottom now if you want to have another look

**Review by tlrsssss — APPROVED** [review]

**Pull request merged**
