### PR TITLE
Add unrealized pnl footer to perp positions

### PR DESCRIPTION
**Pull request by Lou-Kamades**

### CODE REVIEW

**Comment by saml33** [comment]
Looks good. When negative the color should be red (th-down)

Can we see what it looks like with bkg-2 as a background color instead of borders? Might be good to distinguish from other rows. The label can probably be "Total" as the column header does the rest.

We could also add the pnl value tooltip and roe

**Comment by saml33** [comment]
Do you think it looks better with the background or without? I'd lean without I think. The alignment with the label feels a bit off. Could try all on one line

**Comment by Lou-Kamades** [comment]
Personally I like without the background (especially since we are adding the site-wide footer)

**Comment by Lou-Kamades** [comment]
E.g. Screenshot 2023-08-09 at 1 45 39 PM
vs
Screenshot 2023-08-09 at 1 47 14 PM

**Comment by saml33** [comment]
Yeah, the last screenshot looks the best by far. I think ROE should go in the tooltip for all positions and total so it's consistent. Can go after "Total PnL"

**Pull request merged**
