### PR TITLE
orderbook depth chart

### PR DESCRIPTION
**Pull request by saml33**
Changes the layout of the trade chart and adds a depth chart with toggle view.

Screen Shot 2023-07-14 at 8 54 37 am

Screen Shot 2023-07-14 at 9 53 46 am

### CODE REVIEW

**Comment by saml33** [comment]
@tlrsssss should be good now. Fixed a couple of other breakpoint issues we had too

**Comment by tlrsssss** [comment]
Screenshot 2023-07-20 at 11 36 18 AM

^ Small nit: the border is missing from side of Trade tab

I think the tabs are a bit confusing when the depth chart is showing; they end up looking like headers because they are the same width as the columns. In the screenshot above it looks like "Trade" is a heading for the order book and "Book" is the heading for the depth chart. You could keep the tabs a fixed width and justify them to the left similar to the balances, positions, etc tabs:

Screenshot 2023-07-20 at 11 42 20 AM

Feel free to merge as is though, can revisit.

**Comment by tlrsssss** [comment]
I haven't used a depth chart before so tagged @microwavedcola1 for review. Do the axis values and hover values make sense? The red/green coloring on the % hover values isn't intuitive to me.

The only depth chart I've glanced at is dydx and I liked that their tooltip had labels for the values. They had a bit more space to do that though because they overlay it on top of the trading view chart. Something to consider in the future.

Screenshot 2023-07-20 at 11 51 33 AM

**Comment by saml33** [comment]
> Screenshot 2023-07-20 at 11 36 18 AM
> ^ Small nit: the border is missing from side of Trade tab
> 
> I think the tabs are a bit confusing when the depth chart is showing; they end up looking like headers because they are the same width as the columns. In the screenshot above it looks like "Trade" is a heading for the order book and "Book" is the heading for the depth chart. You could keep the tabs a fixed width and justify them to the left similar to the balances, positions, etc tabs:
> 
> Screenshot 2023-07-20 at 11 42 20 AM
> Feel free to merge as is though, can revisit.

This is done. Also added to mobile view

**Comment by saml33** [comment]
> I haven't used a depth chart before so tagged @microwavedcola1 for review. Do the axis values and hover values make sense? The red/green coloring on the % hover values isn't intuitive to me.
> 
> The only depth chart I've glanced at is dydx and I liked that their tooltip had labels for the values. They had a bit more space to do that though because they overlay it on top of the trading view chart. Something to consider in the future.
> 
> Screenshot 2023-07-20 at 11 51 33 AM

Yeah, the labels are a challenge with limited space. This is quite close to Crypto Watch and Binance labels fwiw

**Pull request merged**
